### ISSUE TITLE
2017 Technical Roadmap

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#19]
As written here https://github.com/openstates/meta/wiki/2017-Roadmap we have a fairly ambitious roadmap for this year.  The focus is on sustainability, which starts with getting us off of legacy infrastructure and towards building again.

Another focus not entirely represented in that document is the desire to automate more things so that the project's maintainers are freed up to do other things / actual code.

Big Picture Items:
- [x] all scrapers running for 2017 (Q1)
- [x] automation of more processes [#20] (Q1-Q3)
- [ ] migrate scrapers to pupa (openstates/openstates#1442) (Q1-Q2)
- [ ] [Open States API v2](https://github.com/openstates/meta/projects/1) (Q2-Q3)
- [ ] new data quality tools [#17] (Q2-Q4)
- [ ] notifications [#18] (high priority but we'll likely miss the most relevant window for 2017, so likely Q4)
- [ ] new OpenStates.org (likely Q4-)

**Comment by jamesturk** [comment]
there are separate repos/issues for all of these tasks now, updating 

https://github.com/openstates/meta/wiki/2017-Roadmap to include them
