### ISSUE TITLE
2018 Roadmap

### ISSUE THREAD

**Issue by jamesturk** [openstates/meta#46]
January
- [x] redo geo server
- [x] focus on state sessions

February
- [ ] scraper improvements
- [ ] DQ Tools On Alpha

March
- [ ] Change pupa->billy flow to come from DB
- [ ] new OS.org alpha available

April
- [ ] Open States API v2 beta

May
- [ ] new OS.org beta (likely replaces openstates.org at this point)

June
- [ ] Open States API v2 Final

Q3
- evaluate mapping API v1 calls to v2
- full text search

**Comment by estaub** [comment]
Given what @mileswwatkins and you have written elsewhere, I'd guess that there's unlikely to be any significant effort this year to fix chambers where roll calls either aren't working at all or don't resolve to legislators.  Is that correct?  

The current count is about 28 chambers; see https://github.com/openstates/openstates/issues/1903#issuecomment-365520559 for a list.

**Comment by jamesturk** [comment]
The missing vote scrapers are high priority, I didn't realize we didn't
touch any of them during this year's scraper push but I've tagged them &
filed some new ones.

Name matching is going to be overhauled as part of the new DQ tools, so the
unmatched legislators will probably wait until after that, but I'd expect
to see that improve later this year as well.

**Comment by jamesturk** [comment]
moving over remainder to #50
